dist: trusty
sudo: required
language: ruby
rvm:
  - 2.4.1
jdk:
  - openjdk7
  - oraclejdk8
matrix:
  exclude:
    - rvm: 2.4.0
      jdk: oraclejdk8
    - rvm: 2.3.3
      jdk: oraclejdk8
    - rvm: 2.2.6
      jdk: oraclejdk8
    - rvm: 2.1.9
      jdk: oraclejdk8
    - rvm: 2.0.0
      jdk: oraclejdk8
    - rvm: 1.9.3
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: oraclejdk8
    - rvm: rubinius-3
      jdk: oraclejdk8
    - rvm: rubinius-2
      jdk: oraclejdk8
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
    - rvm: jruby-1.7.26
    - rvm: jruby-head
    - rvm: rubinius-2
script: "bundle exec rake test"
